version: '3.3'

services:
  api_server:
    container_name: api_server
    build: .
    ports:
      - "3035:3001"
    environment: 
      - NODE_ENV=produccion
    networks:
      - mynetwork
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass


networks:
  mynetwork:
    external: true
