version: '3.3'

services:
  api_server:
    container_name: api_server
    build: .
    ports:
      - "3035:3001"
    environment: 
      - NODE_ENV=produccion
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
